server:
  port: 5501

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - '*'
              # PROD
              - 'https://crm.khaiminhland.com/'
              - 'http://10.100.253.1:5504/'
              - 'http://10.100.253.1:5505/'
              - 'http://10.100.253.1:5506/'
              - 'http://10.100.253.1:5507/'
              - 'http://10.100.253.1:5508/'
              - 'http://10.100.253.1:5509/'
              - 'http://10.100.253.1:5510/'
              - 'http://10.100.253.1:5511/'
              - 'http://10.100.253.1:5512/'
              - 'http://10.100.253.1:5513/'
              - 'http://10.100.253.1:5514/'
              - 'http://10.100.253.1:5515/'
            allowedMethods:
              - '*'
            allowedHeaders:
              - '*'
      routes:
        # =====================================
        - id: sso
          uri: lb://sso-service
          predicates:
            - Path=/sso-service/**
        # =====================================
        - id: crm
          uri: lb://crm-service
          predicates:
            - Path=/crm/**
        # =====================================
        - id: notification
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
        # =====================================
        - id: comment
          uri: lb://comment-service
          predicates:
            - Path=/comment/**
        # =====================================
        - id: storage
          uri: lb://storage-service
          predicates:
            - Path=/storage/**
        # =====================================
        - id: bookmark
          uri: lb://bookmark-service
          predicates:
            - Path=/bookmark/**
        # =====================================
        - id: cart
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
        # =====================================
        - id: banner
          uri: lb://banner-service
          predicates:
            - Path=/banner/**
        # =====================================
        - id: bulletin
          uri: lb://bulletin-service
          predicates:
            - Path=/bulletin/**
        # =====================================
        - id: user-permission
          uri: lb://user-permission-service
          predicates:
            - Path=/user-permission/**
        # =====================================
