server:
  port: 5514
  servlet:
    context-path: /notification

spring:
  data:
    mongodb:
      uri: mongodb://mongadmin:1234567890x%40X@10.100.253.4:27017/kml_notification_prod?authSource=admin
      database: kml_notification_prod
  kafka:
    producer:
      acks: 1 # 0: no wait for Kafka response, 1: leader write success, not wait for follower, -1: wait for all leader, and replication
      retries: 1
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
kafka:
  groups:   
    # notification
    fcm-notification-send: khl_dev_send-fcm-notification
    # email
    send-mail-topic: khl_dev_send-mail-topic
  topics:
    # notification
    fcm-notification-send: khl_dev_send-fcm-notification
    # email
    send-mail-topic: khl_dev_send-mail-topic

redis:
  time:
    notification:
      delete: 300
  escape:
    notification:
      delete: khl_prod_delete-notify-prod/
    sms:
      schedule: khl_prod_schedule-sms-prod/
    mail:
      schedule: khl_prod_schedule-mail-prod/
app:
  firebase-config-file: kml-android-firebase-adminsdk-eplp9-e9ef4e0138.json
  tma:
    smsURL: http://10.1.0.156:3008/api/v1/sendSMS

swagger:
  url: http://10.100.253.1:5501
      
static:
  url:
    crm-service: http://10.100.253.1:5508/crm/
avatar:
  url:
    sso-service: http://10.100.253.1:5530/sso/static/images/avatars/
referent-link:
  crm: http://10.100.253.1:5508/crm/
  cart: http://10.100.253.1:5511/cart/
